"use strict";
(() => {
const C=BlobbyCore,$=id=>document.getElementById(id),root=document.documentElement;
let unavailable=false;
function read(k,fallback){try{return JSON.parse(localStorage.getItem(k))??fallback;}catch{return fallback;}}
const state=C.migrate(read);let p=state.prefs,editing=-1,dragFrom=-1,activeCategory="appearance";
const light=matchMedia("(prefers-color-scheme: light)"),reduced=matchMedia("(prefers-reduced-motion: reduce)");
const snow=new C.Snow($("snowCanvas"),{request:f=>requestAnimationFrame(f),cancel:id=>cancelAnimationFrame(id),size:()=>({width:innerWidth,height:innerHeight})});
function save(){state.prefs=p;try{localStorage.setItem("blobby.v3",JSON.stringify(state));$("saveStatus").textContent="Saved automatically on this device";}catch{unavailable=true;$("saveStatus").textContent="Storage unavailable — this session only";$("status").textContent="Storage is unavailable. Your changes work until this page closes.";}}
function el(tag,cls,text){const e=document.createElement(tag);if(cls)e.className=cls;if(text!==undefined)e.textContent=text;return e;}
function button(text,fn,cls=""){const b=el("button",cls,text);b.type="button";b.onclick=fn;return b;}
function say(text){$("status").textContent=text;}
function open(id){$(id).showModal();}
function ask(title,detail,{name=null,accept="Continue"}={}){return new Promise(resolve=>{const d=$("questionDialog");$("questionTitle").textContent=title;$("questionDetail").textContent=detail;$("questionLabel").hidden=name===null;$("questionInput").required=name!==null;$("questionInput").value=name||"";$("questionAccept").textContent=accept;let result=null;
 const done=()=>{d.removeEventListener("close",done);resolve(result);};d.addEventListener("close",done);
 $("questionForm").onsubmit=e=>{e.preventDefault();if(name!==null&&!$("questionInput").value.trim())return;result=name===null?true:$("questionInput").value.trim();d.close();};$("questionCancel").onclick=()=>d.close();d.showModal();(name!==null?$("questionInput"):$("questionCancel")).focus();});}
document.querySelectorAll("[data-close]").forEach(b=>b.onclick=()=>$(b.dataset.close).close());
const categories=[["appearance","Appearance"],["effects","Effects"],["layout","Layout"],["performance","Performance"],["search","Search & Privacy"]];
for(const [id,title]of categories){const b=button(title,()=>showCategory(id));b.id="nav-"+id;b.setAttribute("aria-controls","panel-"+id);$("settingsNav").append(b);const section=el("section","panel");section.id="panel-"+id;section.setAttribute("aria-labelledby","heading-"+id);const h=el("h2","",title);h.id="heading-"+id;section.append(h);$("settingsPanels").append(section);}
function showCategory(id){activeCategory=id;for(const [key]of categories){$("panel-"+key).hidden=id!==key;$("nav-"+key).setAttribute("aria-current",String(id===key));}}
const panel=id=>$("panel-"+id);
function para(parent,text,cls="muted"){const e=el("p",cls,text);parent.append(e);return e;}
function sectionTitle(parent,text){parent.append(el("h3","",text));}
function toggle(parent,key,title,help){const label=el("label","toggle"),input=el("input");input.type="checkbox";input.id=key;input.dataset.pref=key;const span=el("span","",title);if(help)span.append(el("small","",help));label.append(input,span);parent.append(label);return input;}
function select(parent,key,title,options){const label=el("label","field",title),s=el("select");s.id=key;s.dataset.pref=key;for(const [value,text]of options){const o=el("option","",text);o.value=value;s.append(o);}label.append(s);parent.append(label);return s;}
function range(parent,key,title,min,max,step=1,unit=""){const label=el("label","field"),head=el("span","range-label"),out=el("output");out.id=key+"Value";head.append(el("span","",title),out);const input=el("input");input.id=key;input.type="range";input.min=min;input.max=max;input.step=step;input.dataset.pref=key;input.dataset.unit=unit;label.append(head,input);parent.append(label);return input;}
const a=panel("appearance");para(a,"Choose a starting point, then tune it to your taste.");const tg=el("div","theme-grid");tg.id="themeGrid";a.append(tg);
for(const [id,t]of Object.entries(C.themes)){const b=button("",()=>{p.baseTheme=id;p.accent=t.accent;p.mode="preset";changed();},"theme-card");b.dataset.theme=id;b.setAttribute("aria-label","Apply "+t.name+" theme");const preview=el("div","theme-preview");preview.style.background=t.bg;for(const color of [t.panel,t.accent,t.muted]){const i=el("i");i.style.background=color;preview.append(i);}preview.setAttribute("aria-hidden","true");b.append(preview,el("span","",t.name));tg.append(b);}
const apair=el("div","pair");a.append(apair);select(apair,"mode","Color mode",[["preset","Use theme colors"],["dark","Dark"],["light","Light"],["system","Match device"]]);toggle(apair,"large","Larger text","More readable labels and controls.");
const hue=range(a,"hue","Accent hue",0,360,1,"°");delete hue.dataset.pref;hue.className="hue";
const cp=el("div","color-pair"),cl=el("label","field","Picker"),hl=el("label","field","Hex color");const color=el("input"),hex=el("input");color.type="color";color.id="accentPicker";hex.id="accentHex";hex.placeholder="#a5b6ff";hex.maxLength=7;cl.append(color);hl.append(hex);cp.append(cl,hl);a.append(cp);
para(a,"Accent text and button labels adjust for contrast, even with very dark or light colors.","muted");const hexError=para(a,"");hexError.id="hexError";hexError.setAttribute("role","alert");
const aa=el("div","actions");aa.append(button("Restore theme colors",()=>{p.accent=C.themes[p.baseTheme].accent;p.mode="preset";changed();}),button("Save custom theme",()=>savePreset("themes"),"primary"));a.append(aa);sectionTitle(a,"Saved themes");const st=el("div");st.id="savedThemes";a.append(st);a.append(button("Reset appearance",()=>reset("appearance"),"quiet"));
const e=panel("effects");para(e,"Keep things subtle, or add a little atmosphere. Every effect is optional.");const en=para(e,"","notice");en.id="effectNotice";
toggle(e,"effects","Enable page effects","The master switch. Individual selections are kept when switched off.");
for(const [key,title,help]of [["gradient","Background gradient","A soft wash of your accent color."],["animated","Animated gradient","Slow background movement; requires the gradient."],["hover","Hover movement","Gentle lift on buttons and shortcuts."],["shadows","Soft shadows","Subtle depth around panels."],["glow","Search glow","A soft accent glow while searching."],["glass","Glass panels","Translucent panels with background blur."],["entrance","Entrance animation","A brief fade when the homepage opens."],["snow","Falling snow","Off by default. Particles stay behind the page controls."]])toggle(e,key,title,help);
range(e,"density","Snow density",10,100,5," flakes");range(e,"speed","Snow speed",.3,2,.1,"×");
const l=panel("layout");para(l,"Choose a layout, adjust its proportions, and save your own version.");const lg=el("div","layout-grid");lg.id="layoutGrid";l.append(lg);
const descriptions={centered:"Balanced search and shortcuts",compact:"Tighter spacing, smaller tiles",dashboard:"Separate shortcut and recent panels",minimal:"Branding and search only"};
for(const [id,v]of Object.entries(C.layouts)){const b=button("",()=>{Object.assign(p,C.pick(v,C.layoutKeys));changed();},"layout-card");b.dataset.layout=id;const preview=el("div","layout-preview "+id);preview.setAttribute("aria-hidden","true");for(let i=0;i<3;i++)preview.append(el("i"));b.append(preview,el("span","",v.name),el("small","",descriptions[id]));lg.append(b);}
range(l,"width","Content width",600,1280,20," px");range(l,"gap","Spacing",6,32,2," px");range(l,"tile","Shortcut height",56,160,2," px");range(l,"cols","Desktop columns",1,6,1,"");
toggle(l,"showShortcuts","Show shortcuts","Your saved shortcuts remain when hidden.");toggle(l,"showRecent","Show recently opened pages","Temporarily hidden in performance mode.");toggle(l,"subtitle","Show “made by panga”","Display the credit below the title.");const ln=para(l,"","notice");ln.id="layoutNotice";
l.append(button("Edit and reorder shortcuts",openEditor));sectionTitle(l,"Saved layouts");const sl=el("div");sl.id="savedLayouts";l.append(sl);const la=el("div","actions");la.append(button("Restore default layout",()=>reset("layout")),button("Save custom layout",()=>savePreset("layouts"),"primary"));l.append(la);
const f=panel("performance");para(f,"Less work for your device, without losing your settings.");toggle(f,"fast","Performance mode","Stops snow, cancels its animation loop, and releases its particles. Disables gradients, animations, shadows, glow, blur, and shortcut icons.");
para(f,"Recent-page rendering and suggestions also pause. Search, shortcut navigation, recording preferences, and settings remain available. Your chosen effects and layout return when you switch this off.","notice");
para(f,"This changes this homepage only. It cannot speed up other websites, block their ads, or change native WebView memory settings.");const runtime=para(f,"","notice");runtime.id="runtimeStatus";
const s=panel("search");para(s,"Choose how you search and what this homepage remembers.");select(s,"engine","Search engine",Object.entries(C.engines).map(([k,v])=>[k,v[0]]));toggle(s,"remember","Remember pages opened here","Save up to 20 entries. Switching off stops future recording; existing entries remain.");toggle(s,"autofocus","Focus search on desktop","Ready to type when you return. No automatic mobile keyboard.");s.append(button("Clear recent pages",clearRecent));para(s,"Press / to focus search, Enter to go, or Escape to close a window. Websites open in this same tab or WebView.");
para(s,"Preferences are stored in this browser, not in an online account. Moving to a different website address starts a separate set of preferences.");s.append(button("Reset all settings",()=>reset("all"),"quiet"));
function changed(persist=true){apply();if(persist)save();}
function actualTheme(){if(p.mode==="light"||(p.mode==="system"&&light.matches))return C.themes.arctic;if(p.mode==="dark"&&C.themes[p.baseTheme].mode==="light"||p.mode==="system"&&!light.matches&&C.themes[p.baseTheme].mode==="light")return C.themes.midnight;return C.themes[p.baseTheme];}
function apply(){const t=actualTheme(),fx=C.effective(p,reduced.matches,document.hidden);
 for(const key of ["bg","panel","ink","muted","line"])root.style.setProperty("--"+key,t[key]);
 root.style.colorScheme=t.mode;root.style.setProperty("--accent",p.accent);root.style.setProperty("--accent-text",C.readableAccent(p.accent,t));root.style.setProperty("--accent-ink",C.contrast(p.accent,"#000000")>=C.contrast(p.accent,"#ffffff")?"#000000":"#ffffff");root.style.setProperty("--glow",p.accent+"55");root.style.setProperty("--glass",t.panel+"ed");
 for(const [key,suffix]of [["width","px"],["gap","px"],["tile","px"],["cols",""]])root.style.setProperty("--"+key,p[key]+suffix);
 for(const [key,value]of Object.entries({...fx,fast:p.fast,large:p.large,layout:p.layout,hidden:document.hidden,reduced:reduced.matches}))root.dataset[key]=String(value);
 $("subtitle").hidden=!p.subtitle;$("fastBadge").hidden=!p.fast;$("searchHint").textContent="Search with "+C.engines[p.engine][0]+" or enter a website.";
 syncControls();renderLinks();renderRecent();updateSnow();
}
function syncControls(){for(const input of document.querySelectorAll("[data-pref]")){const k=input.dataset.pref;if(input.type==="checkbox")input.checked=p[k];else input.value=String(p[k]);if($(k+"Value"))$(k+"Value").textContent=p[k]+(input.dataset.unit||"");}
 $("hue").value=C.hueOf(p.accent);$("hueValue").textContent=C.hueOf(p.accent)+"°";$("accentPicker").value=p.accent;if(document.activeElement!==$("accentHex"))$("accentHex").value=p.accent;
 const blocked=p.fast||!p.effects;for(const k of ["gradient","animated","hover","shadows","glow","glass","entrance","snow","density","speed"]){$(k).disabled=blocked||(reduced.matches&&["animated","hover","entrance","snow","density","speed"].includes(k))||(k==="animated"&&!p.gradient)||(["density","speed"].includes(k)&&!p.snow);}
 $("effects").disabled=p.fast;$("showRecent").disabled=p.fast;
 $("effectNotice").textContent=p.fast?"Performance mode overrides all effects. Your selections are preserved.":!p.effects?"The master effects switch is off. Your selections are preserved.":reduced.matches?"Your device requests reduced motion. Snow and movement are paused. Static effects remain available.":"Effects are enabled. Animations pause when this page is not visible.";
 $("layoutNotice").hidden=!p.fast;$("layoutNotice").textContent="Performance mode hides recent pages and shortcut icons. Your layout settings are kept.";
 for(const b of document.querySelectorAll("[data-theme]"))b.setAttribute("aria-pressed",String(p.baseTheme===b.dataset.theme));
 for(const b of $("layoutGrid").children){const v=C.layouts[b.dataset.layout];b.setAttribute("aria-pressed",String(C.layoutKeys.every(k=>p[k]===v[k])));}
}
for(const input of document.querySelectorAll("[data-pref]")){const key=input.dataset.pref;const update=()=>{p[key]=input.type==="checkbox"?input.checked:input.type==="range"?Number(input.value):input.value;changed(input.type!=="range");};input.addEventListener(input.type==="range"?"input":"change",update);if(input.type==="range")input.addEventListener("change",save);}
$("hue").oninput=()=>{p.accent=C.hueColor($("hue").value);changed(false);};$("hue").onchange=save;
$("accentPicker").oninput=()=>{p.accent=$("accentPicker").value;changed(false);};$("accentPicker").onchange=save;
$("accentHex").oninput=()=>{const h=C.hex($("accentHex").value);$("hexError").textContent=h?"":"Use a hex color such as #a5b6ff.";if(h){p.accent=h;changed(false);}};$("accentHex").onchange=()=>{if(C.hex($("accentHex").value))save();else{$("accentHex").value=p.accent;$("hexError").textContent="Invalid color was not applied.";}};
async function savePreset(kind){const list=state[kind];if(list.length>=20){await ask("Saved preset limit","You can save up to 20. Delete one to make room.",{accept:"OK"});return;}const name=await ask(kind==="themes"?"Save custom theme":"Save custom layout","Choose a name you will recognize.",{name:"",accept:"Save"});if(!name)return;if(list.some(x=>x.name.toLowerCase()===name.toLowerCase())){await ask("Name already used","Use Rename on the existing preset, or choose another name.",{accept:"OK"});return;}list.push({name,values:C.pick(p,kind==="themes"?C.appearanceKeys:C.layoutKeys),...(kind==="layouts"?{order:state.links.map(x=>x.url)}:{})});save();renderPresets();}
function renderPresets(){for(const kind of ["themes","layouts"]){const parent=$(kind==="themes"?"savedThemes":"savedLayouts");parent.replaceChildren();if(!state[kind].length)para(parent,"No saved "+kind+" yet.","muted");
 state[kind].forEach((item,index)=>{const row=el("div","saved-row");row.append(button(item.name,()=>{Object.assign(p,item.values);if(kind==="layouts")state.links=C.restoreOrder(state.links,item.order||[]);changed();}),button("Rename",async()=>{const name=await ask("Rename preset","Give this preset a new name.",{name:item.name,accept:"Rename"});if(name&&!state[kind].some((x,i)=>i!==index&&x.name.toLowerCase()===name.toLowerCase())){item.name=name;save();renderPresets();}else if(name)await ask("Name already used","Choose a unique name.",{accept:"OK"});}),button("Delete",async()=>{if(await ask("Delete "+item.name+"?","This removes the saved preset. Your current appearance and layout stay.",{accept:"Delete"})){state[kind].splice(index,1);save();renderPresets();}}));parent.append(row);});}}
async function reset(kind){const detail=kind==="appearance"?"Restore the default appearance and effects. Saved custom themes and layouts stay.":kind==="layout"?"Restore the centered layout. Saved layouts and shortcuts stay.":"Restore all settings and delete saved custom themes and layouts. Shortcuts and recent pages stay.";
 if(!await ask("Reset "+(kind==="all"?"all settings":kind)+"?",detail,{accept:"Reset"}))return;
 if(kind==="all"){p=C.clone(C.defaults);state.themes=[];state.layouts=[];}else Object.assign(p,C.pick(C.defaults,kind==="appearance"?C.appearanceKeys:C.layoutKeys));
 changed();renderPresets();
}
function logVisit(label,url){if(!p.remember)return;state.recent=[{label,url,time:Date.now()},...state.recent.filter(x=>x.url!==url)].slice(0,20);save();}

// Lightweight tabbed browser shell. Each tab owns its own iframe so switching tabs preserves its page.
const browser={tabs:[],active:null,nextId:1,maxTabs:8};
function tabTitle(tab){if(!tab.url)return "New tab";try{return new URL(tab.url).hostname.replace(/^www\./,"")||"Page";}catch{return "Page";}}
function makeFrame(tab){const frame=el("iframe","browser-frame");frame.id="browser-frame-"+tab.id;frame.title="Browser tab: "+tabTitle(tab);frame.referrerPolicy="strict-origin-when-cross-origin";frame.setAttribute("allow","clipboard-read; clipboard-write; fullscreen");frame.hidden=true;$("browserFrames").append(frame);tab.frame=frame;}
function createTab(url=null,activate=true){if(browser.tabs.length>=browser.maxTabs){say("You can open up to "+browser.maxTabs+" tabs.");return null;}const tab={id:browser.nextId++,url:null,history:[null],index:0,frame:null};browser.tabs.push(tab);makeFrame(tab);if(activate)switchTab(tab.id);if(url)navigate(url,tab);else syncBrowser();return tab;}
function activeTab(){return browser.tabs.find(t=>t.id===browser.active)||null;}
function switchTab(id){if(!browser.tabs.some(t=>t.id===id))return;browser.active=id;syncBrowser();}
function closeTab(id){const i=browser.tabs.findIndex(t=>t.id===id);if(i<0)return;const wasActive=browser.active===id;browser.tabs[i].frame?.remove();browser.tabs.splice(i,1);if(!browser.tabs.length){createTab();return;}if(wasActive)browser.active=browser.tabs[Math.min(i,browser.tabs.length-1)].id;syncBrowser();}
function setTabUrl(tab,url,fromHistory=false){tab.url=url;if(tab.frame){if(url){tab.frame.src=url;tab.frame.hidden=false;tab.frame.title="Browser tab: "+tabTitle(tab);}else{tab.frame.src="about:blank";tab.frame.hidden=true;}}if(!fromHistory){tab.history=tab.history.slice(0,tab.index+1);tab.history.push(url);tab.index=tab.history.length-1;}syncBrowser();}
function navigate(raw,tab=activeTab()){if(!tab)return;const url=C.resolve(raw,p.engine);if(!url){say("Enter a search or a valid http/https website address.");return;}logVisit(String(raw).trim(),url);setTabUrl(tab,url);}
function browserBack(){const t=activeTab();if(!t||t.index<=0)return;t.index--;setTabUrl(t,t.history[t.index],true);}
function browserForward(){const t=activeTab();if(!t||t.index>=t.history.length-1)return;t.index++;setTabUrl(t,t.history[t.index],true);}
function browserHome(){const t=activeTab();if(!t)return;setTabUrl(t,null);}
function browserRefresh(){const t=activeTab();if(!t)return;if(!t.url){location.reload();return;}const u=t.url;t.frame.src="about:blank";requestAnimationFrame(()=>{t.frame.src=u;});}
function syncBrowser(){const list=$("tabList");list.replaceChildren();for(const tab of browser.tabs){const wrap=el("div","browser-tab");wrap.setAttribute("role","presentation");wrap.setAttribute("aria-selected",String(tab.id===browser.active));const b=el("button","browser-tab-main");b.type="button";b.setAttribute("role","tab");b.setAttribute("aria-selected",String(tab.id===browser.active));b.onclick=()=>switchTab(tab.id);b.append(el("span","browser-tab-title",tabTitle(tab)));const x=el("button","tab-close","×");x.type="button";x.setAttribute("aria-label","Close "+tabTitle(tab));x.onclick=()=>closeTab(tab.id);wrap.append(b,x);list.append(wrap);if(tab.frame)tab.frame.hidden=tab.id!==browser.active||!tab.url;}
 const t=activeTab();const viewing=!!t?.url;document.body.classList.toggle("browser-view",viewing);$("browserFrames").hidden=!viewing;$("embedNotice").hidden=!viewing;$("addressBar").value=t?.url||"";$("backButton").disabled=!t||t.index<=0;$("forwardButton").disabled=!t||t.index>=t.history.length-1;$("refreshButton").disabled=!t;$("externalButton").disabled=!viewing;$("newTab").disabled=browser.tabs.length>=browser.maxTabs;}
$("newTab").onclick=()=>createTab();$("backButton").onclick=browserBack;$("forwardButton").onclick=browserForward;$("refreshButton").onclick=browserRefresh;$("homeButton").onclick=browserHome;$("externalButton").onclick=()=>{const t=activeTab();if(t?.url)window.open(t.url,"_blank","noopener,noreferrer");};
$("addressForm").onsubmit=e=>{e.preventDefault();navigate($("addressBar").value);};
createTab();
function anchor(item,cls){const a=el("a",cls);a.href=item.url;a.addEventListener("click",e=>{e.preventDefault();navigate(item.url);});return a;}
function renderLinks(){const host=$("shortcuts");host.replaceChildren();$("shortcutSection").hidden=!p.showShortcuts;if(!p.showShortcuts)return;
 state.links.forEach(item=>{const a=anchor(item,"surface tile");if(!p.fast){const icon=el("span","initial",item.label.slice(0,1).toUpperCase());icon.setAttribute("aria-hidden","true");a.append(icon);}a.append(el("span","tile-name",item.label));host.append(a);});if(!state.links.length)host.append(el("p","empty","Add your first shortcut with Edit shortcuts."));}
function renderRecent(){const host=$("recent");host.replaceChildren();$("suggestions").replaceChildren();$("recentSection").hidden=p.fast||!p.showRecent;$("sections").classList.toggle("single",!p.showShortcuts||p.fast||!p.showRecent);if(p.fast)return;
 for(const item of state.recent.slice(0,5)){const o=el("option");o.value=item.url;$("suggestions").append(o);}if(!p.showRecent)return;$("clearButton").hidden=!state.recent.length;
 state.recent.slice(0,8).forEach((item,index)=>{const row=el("div","recent-row"),a=anchor(item,"");a.append(el("strong","",item.label),el("small","",new URL(item.url).hostname+(item.time?" · "+new Date(item.time).toLocaleDateString():"")));const remove=button("×",()=>{state.recent.splice(index,1);save();renderRecent();},"quiet");remove.setAttribute("aria-label","Remove "+item.label);row.append(a,remove);host.append(row);});
 if(!state.recent.length)host.append(el("p","empty",p.remember?"Pages opened here will appear in this list.":"Recording is off. Change it in Search & Privacy."));}
async function clearRecent(){if(await ask("Clear recently opened pages?","This clears only this homepage’s list, not browser history elsewhere.",{accept:"Clear"})){state.recent=[];save();renderRecent();}}
$("clearButton").onclick=clearRecent;
$("searchForm").onsubmit=e=>{e.preventDefault();const text=$("query").value;if(!text.trim()){say("Enter a search or a valid http/https website address.");return;}navigate(text);$("query").value="";};
function cancelEdit(){editing=-1;$("shortcutForm").reset();$("editTitle").textContent="Add shortcut";$("saveShortcut").textContent="Add shortcut";$("shortcutError").textContent="";}
function move(from,to){state.links=C.reorder(state.links,from,to);save();cancelEdit();editor();renderLinks();const rows=$("shortcutEditor").children;if(rows[to])rows[to].querySelector("button").focus();}
function editor(){const host=$("shortcutEditor");host.replaceChildren();state.links.forEach((item,index)=>{const row=el("div","edit-row");row.draggable=true;row.append(el("span","",item.label));
 const up=button("↑",()=>move(index,index-1)),down=button("↓",()=>move(index,index+1));up.disabled=index===0;down.disabled=index===state.links.length-1;up.setAttribute("aria-label","Move "+item.label+" up");down.setAttribute("aria-label","Move "+item.label+" down");
 row.append(up,down,button("Edit",()=>{editing=index;$("shortcutName").value=item.label;$("shortcutUrl").value=item.url;$("editTitle").textContent="Edit shortcut";$("saveShortcut").textContent="Save shortcut";$("shortcutName").focus();}),button("Remove",async()=>{if(await ask("Remove "+item.label+"?","You can add it again later.",{accept:"Remove"})){state.links.splice(index,1);save();cancelEdit();editor();renderLinks();}}));
 row.ondragstart=e=>{dragFrom=index;e.dataTransfer.setData("text/plain",String(index));e.dataTransfer.effectAllowed="move";};row.ondragover=e=>{if(dragFrom>=0){e.preventDefault();row.classList.add("drag-over");}};row.ondragleave=()=>row.classList.remove("drag-over");row.ondrop=e=>{e.preventDefault();row.classList.remove("drag-over");if(dragFrom>=0)move(dragFrom,index);dragFrom=-1;};row.ondragend=()=>{dragFrom=-1;document.querySelectorAll(".drag-over").forEach(x=>x.classList.remove("drag-over"));};host.append(row);});}
function openEditor(){cancelEdit();editor();open("shortcutDialog");}
$("manageButton").onclick=openEditor;$("cancelEdit").onclick=cancelEdit;
$("shortcutForm").onsubmit=e=>{e.preventDefault();const label=$("shortcutName").value.trim();let raw=$("shortcutUrl").value.trim();if(!/^[a-z][a-z0-9+.-]*:/i.test(raw))raw="https://"+raw;const url=C.safeUrl(raw);if(!url||!label){$("shortcutError").textContent="Enter a name and a valid http/https website address.";return;}if(editing<0&&state.links.length>=12){$("shortcutError").textContent="You have 12 shortcuts. Remove one to make room.";return;}if(state.links.some((x,i)=>i!==editing&&x.url===url)){$("shortcutError").textContent="This website is already in your shortcuts.";return;}if(editing>=0)state.links[editing]={label,url};else state.links.push({label,url});save();cancelEdit();editor();renderLinks();};
function updateSnow(){const fx=C.effective(p,reduced.matches,document.hidden);snow.configure(fx.snow,p.density,p.speed,actualTheme().mode==="light"?"#526780":"#ffffff");$("runtimeStatus").textContent=p.fast?"Performance mode active: no decorative animation loops or snow particles.":fx.snow?"Snow running: "+snow.particles.length+" particles. It stops when you leave this page.":"No snow animation loop is running.";}
document.addEventListener("visibilitychange",()=>{root.dataset.hidden=String(document.hidden);const fx=C.effective(p,reduced.matches,document.hidden);root.dataset.animated=String(fx.animated);updateSnow();});
window.addEventListener("pagehide",()=>snow.stop());window.addEventListener("resize",()=>{if(p.snow)updateSnow();});
function focusSearch(){if(p.autofocus&&matchMedia("(pointer:fine)").matches&&!document.querySelector("dialog[open]"))$("query").focus();}
window.addEventListener("pageshow",()=>{renderRecent();updateSnow();focusSearch();});
for(const media of [light,reduced]){if(media.addEventListener)media.addEventListener("change",apply);else if(media.addListener)media.addListener(apply);}
document.addEventListener("keydown",e=>{if(e.key==="/"&&!document.querySelector("dialog[open]")&&!["INPUT","TEXTAREA","SELECT","BUTTON"].includes(document.activeElement.tagName)&&!document.activeElement.isContentEditable){e.preventDefault();$("query").focus();}});
$("settingsButton").onclick=()=>{syncControls();open("settings");};
showCategory(activeCategory);renderPresets();apply();save();focusSearch();
})();
